# Workaround for Travis CI issue 5227, which results in a buffer overflow
# caused by Java when running the build on OpenJDK.
# https://github.com/travis-ci/travis-ci/issues/5227
before_install:
    - cat /etc/hosts # optionally check the content *before*
    - sudo hostname "$(hostname | cut -c1-63)"
    - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
    - cat /etc/hosts # optionally check the content *after*
sudo: false
language: java
dist: precise
env:
  global:
    - GRADLE_OPTS="-Xmx512m"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  ./gradlew check --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Workaround for Travis CI issue 5227 causing buffer overflow in OpenJDK7.
before_install:
    - sudo hostname "$(hostname | cut -c1-63)"
    - sed -e "s/^\\(127\\.0\\.0\\.1.*\\)/\\1 $(hostname | cut -c1-63)/" /etc/hosts | sudo tee /etc/hosts
