sudo: false
language: java
env:
  global:
    - GRADLE_OPTS="-Xmx512m"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
script:
  ./gradlew check --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
