sudo: false
language: java
dist: precise
git:
  depth: 2
env:
  global:
    - GRADLE_OPTS="-Xmx512m"
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
cache:
  directories:
    - $HOME/.gradle
    - $HOME/.m2
    - ./build
    - ./.gradle
script:
  ./gradlew check --info
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Workaround for Travis CI issue 5227 causing buffer overflow in OpenJDK7.
addons:
  hosts:
    - workaround
  hostname: workaround
